theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/singularitti/Spglib.jl/archive/refs/tags/v0.4.0.zip
  tar_url: https://github.com/singularitti/Spglib.jl/archive/refs/tags/v0.4.0.tar.gz
