name = "Spglib"
uuid = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.9.4"

[deps]
CrystallographyCore = "80545937-1184-4bc9-b283-396e91386b5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
spglib_jll = "ac4a9f1e-bdb2-5204-990c-47c8b2f70d4e"

[compat]
CrystallographyCore = "0.1, 0.2, 0.3, 0.6"
StaticArrays = "0.8.3, 0.9, 0.10, 0.11, 0.12, 1.0"
StructEquality = "1, 2"
julia = "1.3"
spglib_jll = "2 - 2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
